#!/bin/bash

HOSTNAME=`cat /etc/hostname`
TIMEZONE=`timedatectl | grep "Time zone" | awk '{print $3 $4 $5}'`
USER=`whoami`
OS=`cat /proc/version | awk '{print $1,$3,$4}'`
DATE=`date +"%d %b %Y %T"`
UPTIME=`uptime -p`
UPTIME_SEC=`cat /proc/uptime | awk '{print $2}'`
IP=`ip r | grep default | awk '/default/ {print $9}'`
NET_INTERFACE=`ip r | grep default | awk '/default/ {print $5}'`
MASK=`ifconfig $NET_INTERFACE | grep netmask | awk '{print $4}'`
GATEWAY=`ip r | grep default | awk '/default/ {print $3}'`
# **GATEWAY** = _ip шлюза по умолчанию_  
# **RAM_TOTAL** = _размер оперативной памяти в Гб c точностью три знака после запятой в виде: **3.125 GB**_  
# **RAM_USED** = _размер используемой памяти в Гб c точностью три знака после запятой_  
# **RAM_FREE** = _размер свободной памяти в Гб c точностью три знака после запятой_  
# **SPACE_ROOT** = _размер рутового раздела в Mб с точностью два знака после запятой в виде: **254.25 MB**_  
# **SPACE_ROOT_USED** = _размер занятого пространства рутового раздела в Mб с точностью два знака после запятой_  
# **SPACE_ROOT_FREE** = _размер свободного пространства рутового раздела в Mб с точностью два знака после запятой_
echo "**HOSTNAME**     = $HOSTNAME"
echo "**TIMEZONE**     = $TIMEZONE" 
echo "**USER**         = $USER"
echo "**OS**           = $OS"
echo "**DATE**         = $DATE"
echo "**UPTIME**       = $UPTIME"
echo "**UPTIME_SEC**   = $UPTIME_SEC"
echo "**IP**           = $IP"
echo "**MASK**         = $MASK"
echo "**GATEWAY**      = $GATEWAY"